language: scala
scala:
- 2.10.7
- 2.11.12
- 2.12.4
- 2.13.0-M1
jdk:
- oraclejdk8
script: scripts/travis.sh
sudo: false
cache:
  directories:
  - $HOME/.coursier
  - $HOME/.ivy2/cache
  - $HOME/.sbt
env:
  global:
  - secure: SHhR2GjIZ5prfuTujGreZAe+9nJkly2Eu1HP9hYQ4ntGFCz+9hcQ9ZDj532Yye3HItDzhE8wUA5HuL58+GivA72w7dbqMgoE9EvRAZrxPDRb1kvNN+HOHo6+t08DUPBh8jfH/VqNGjEKMRT70UjLWA1hi1rEZAi2J4OlTXkKmGc=
  - secure: iAA98AVcqwTd11RjJaA133t38gqoGDsnLP2m1Hm2PFrUGE1AXg1/0wX6bXmFCnj+NIfb2ItC9cyuepcvrfAfV4ukU66Yyh6DCgYaup6IhrgSCdck5zZcc2KrxsLyWVAyuClu7TG6xbjHc4os0hZZ0w95pUIG2sOyr4faH1GbeUQ=
branches:
  only:
  - master

matrix:
  include:
  - scala: 2.11.12
    dist: trusty
    sudo: required
    env: NATIVE=1
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/e9df70ce671c58f34eab530a44875d6f818ba8fe/bin/travis_setup.sh | bash -x
