language: scala
jdk:
- oraclejdk8
before_install:
- git fetch --tags
script: scripts/travis.sh
sudo: false
cache:
  directories:
  - $HOME/.cache
  - $HOME/.coursier
  - $HOME/.ivy2/cache
  - $HOME/.sbt
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - scala: 2.11.12
  - scala: 2.12.8
  - scala: 2.13.0-M5
  - scala: 2.11.12
    dist: trusty
    sudo: required
    env: NATIVE=1
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
  - stage: release
    script: sbt ci-release
