language: scala
jdk:
  - openjdk8
  - openjdk11
scala:
  - 2.12.11
  - 2.13.2
git:
  depth: false
script: sbt ++${TRAVIS_SCALA_VERSION} test mimaReportBinaryIssues
sudo: false
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - stage: release
    script: sbt ci-release
    jdk: openjdk11
